import { setupWorker } from "msw/browser";
import { handlers } from "./handlers.js";

/**
 * Browser Service Worker for mock mode. The web app imports this only behind the
 * `VITE_MOCKS` flag via dynamic import, so the production bundle eliminates all
 * mock code (ADR 0006). Requires `mockServiceWorker.js` to be present in the
 * app's public assets (generated by `msw init`).
 */
export const worker = setupWorker(...handlers);
