import { MOCKS } from "./env.js";

/**
 * Starts the MSW browser worker in mock mode. Imported only behind `VITE_MOCKS`
 * via dynamic import so the bundler eliminates all mock code from the production
 * build (ADR 0006). Requires `public/mockServiceWorker.js` (generated by
 * `pnpm dlx msw init`).
 */
export async function startMocks(): Promise<void> {
  if (!MOCKS) {
    return;
  }
  const { worker } = await import("@spend-circle/mocks/worker");
  await worker.start({ onUnhandledRequest: "bypass" });
}
